"""create restaurants table

Revision ID: 09bbb8e735eb
Revises: 4d63e2fbed63
Create Date: 2026-08-19 17:32:57.030277

"""
import geoalchemy2  # noqa: F401
import sqlalchemy as sa

from alembic import op

revision = '09bbb8e735eb'
down_revision = '4d63e2fbed63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(
        geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT',
        name='geometry'), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('business_hours', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True),
              server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True),
              server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_restaurants_source_source_id')
    )
    # 注意：本环境 alembic+asyncpg 会对 gist 索引语句双执行（第二次报 already exists），
    # 因此使用 IF NOT EXISTS 保证幂等
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_restaurants_location "
        "ON restaurants USING gist (location)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_restaurants_location")
    op.drop_table('restaurants')
    # ### end Alembic commands ###
