"""widen restaurants phone column

Revision ID: 513f9bcbb136
Revises: 09bbb8e735eb
Create Date: 2026-08-20 08:58:53.694931

"""
import sqlalchemy as sa

from alembic import op

revision = '513f9bcbb136'
down_revision = '09bbb8e735eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'phone',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'phone',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
