"""create reviews and group_restaurants tables

Revision ID: d71862f1629e
Revises: f5d400409e30
Create Date: 2026-08-20 10:43:45.993730

"""
import sqlalchemy as sa

from alembic import op

revision = 'd71862f1629e'
down_revision = 'f5d400409e30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_restaurants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('restaurant_id', sa.BigInteger(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('last_visit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('group_score', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('taste_score', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('value_score', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('environment_score', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('service_score', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('traffic_score', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True),
              server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True),
              server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'restaurant_id', name='uq_group_restaurants_group_restaurant')
    )
    op.create_index(op.f('ix_group_restaurants_group_id'),
                    'group_restaurants', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_restaurants_restaurant_id'),
                    'group_restaurants', ['restaurant_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('taste_score', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('value_score', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('environment_score', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('service_score', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('traffic_score', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True),
              server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True),
              server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_reviews_event_user')
    )
    op.create_index(op.f('ix_reviews_event_id'), 'reviews', ['event_id'], unique=False)
    op.create_index(op.f('ix_reviews_group_id'), 'reviews', ['group_id'], unique=False)
    op.create_index(op.f('ix_reviews_restaurant_id'), 'reviews', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_restaurant_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_group_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_event_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_group_restaurants_restaurant_id'), table_name='group_restaurants')
    op.drop_index(op.f('ix_group_restaurants_group_id'), table_name='group_restaurants')
    op.drop_table('group_restaurants')
    # ### end Alembic commands ###
